# Generated by Django 5.0.3 on 2024-03-09 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmaterials',
            options={'verbose_name': 'Product Materials', 'verbose_name_plural': 'Product Materials'},
        ),
        migrations.AlterModelOptions(
            name='unitys',
            options={'verbose_name': 'Unitys', 'verbose_name_plural': 'Unitys'},
        ),
    ]
