# Generated by Django 5.0.3 on 2024-03-09 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productmaterials_options_alter_unitys_options'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Warehose',
            new_name='Warehouse',
        ),
        migrations.RenameField(
            model_name='warehouse',
            old_name='qty',
            new_name='remainder',
        ),
    ]
